"""アプリ全体で共有する定数と設定。"""

from __future__ import annotations

import os
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent
PROJECT_DIR = BACKEND_DIR.parent

try:
    from dotenv import load_dotenv

    load_dotenv(PROJECT_DIR / ".env")
except ImportError:
    pass


DATA_DIR = BACKEND_DIR / "data"
MAP_CACHE_DIR = DATA_DIR / "map_cache"
OSMNX_CACHE_DIR = DATA_DIR / "osmnx_cache"
CHECKPOINT_DIR = DATA_DIR / "checkpoints"
EXPORT_DIR = DATA_DIR / "exports"
UPLOAD_DIR = DATA_DIR / "uploads"

for _d in (DATA_DIR, MAP_CACHE_DIR, OSMNX_CACHE_DIR, CHECKPOINT_DIR, EXPORT_DIR, UPLOAD_DIR):
    _d.mkdir(parents=True, exist_ok=True)


CHECKPOINT_PATH = CHECKPOINT_DIR / "shared_policy.pt"

HOST = os.getenv("DRIVERL_HOST", "127.0.0.1")
PORT = int(os.getenv("DRIVERL_PORT", "8000"))

PROTOCOL_VERSION = 1

CORS_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

SIM_HZ = 20.0
DT = 1.0 / SIM_HZ

METRICS_HZ = 1.0

MAX_VEHICLES = 8
MAX_OBSTACLES = 64

MAX_EPISODE_STEPS = 4000

VEHICLE_LENGTH = 4.4
VEHICLE_WIDTH = 1.8
VEHICLE_HEIGHT = 1.45
WHEELBASE = 2.6

MAX_STEER = 0.55
MAX_ACCEL = 3.0
MAX_DECEL = -6.0
MAX_SPEED = 13.9
STEER_RATE = 2.5

MAX_LATERAL_ACCEL = 4.5

OBSTACLE_RADIUS = 0.35
OBSTACLE_HEIGHT = 0.75

OBS_SELF_DIM = 2
OBS_GOAL_DIM = 3
OBS_ROUTE_POINTS = 5
OBS_ROUTE_DIM = OBS_ROUTE_POINTS * 2

OBS_LANE_DIM = 4

OBS_SIGNAL_DIM = 5

OBS_SIGN_DIM = 3

OBS_VEHICLE_COUNT = 3
OBS_VEHICLE_FIELDS = 4
OBS_VEHICLE_DIM = OBS_VEHICLE_COUNT * OBS_VEHICLE_FIELDS

OBS_OBSTACLE_COUNT = 3
OBS_OBSTACLE_FIELDS = 3
OBS_OBSTACLE_DIM = OBS_OBSTACLE_COUNT * OBS_OBSTACLE_FIELDS

OBS_FREESPACE_DIM = 9

OBS_DIM = (
    OBS_SELF_DIM
    + OBS_GOAL_DIM
    + OBS_ROUTE_DIM
    + OBS_LANE_DIM
    + OBS_SIGNAL_DIM
    + OBS_SIGN_DIM
    + OBS_VEHICLE_DIM
    + OBS_OBSTACLE_DIM
    + OBS_FREESPACE_DIM
)

ACTION_DIM = 2

OBS_ROUTE_SPACING = 6.0
OBS_VEHICLE_RANGE = 40.0
OBS_OBSTACLE_RANGE = 30.0
OBS_FREESPACE_MAX_DISTANCE = 30.0
OBS_GOAL_RANGE = 300.0
OBS_LATERAL_RANGE = 8.0
OBS_SIGNAL_RANGE = 60.0

DETECTOR_DIR = DATA_DIR / "detector"
DETECTOR_PATH = DETECTOR_DIR / "detector.keras"
DETECTOR_DATASET_DIR = DETECTOR_DIR / "dataset"
DETECTOR_DIR.mkdir(parents=True, exist_ok=True)

PERCEP_MAX_DETECTIONS = 12

PERCEP_CONF_THRESHOLD = 0.35

PERCEP_FALLBACK_GROUND_TRUTH = True

GOAL_RADIUS = 8.0
OFFROAD_LIMIT = 12.0

SIGNAL_STOP_TOLERANCE_M = 1.0

PPO_HIDDEN_SIZES = (128, 128)
PPO_HIDDEN_MIN_LAYERS = 1
PPO_HIDDEN_MAX_LAYERS = 4
PPO_HIDDEN_MIN_WIDTH = 16
PPO_HIDDEN_MAX_WIDTH = 512
PPO_EPOCHS = 4
PPO_MINIBATCHES = 4

PPO_MINIBATCHES_PER_STEP = 1

FRAME_HZ = 60.0
PPO_GAE_LAMBDA = 0.95
PPO_VALUE_COEF = 0.5
PPO_MAX_GRAD_NORM = 0.5
PPO_LOG_STD_INIT = -0.5
PPO_LOG_STD_MIN = -5.0
PPO_LOG_STD_MAX = 0.0

TORCH_NUM_THREADS = 4

LANE_DEPARTURE_M = 1.75
LANE_RETURN_M = 1.25

SIGNAL_GREEN_SEC = 25.0
SIGNAL_YELLOW_SEC = 3.0
SIGNAL_ALL_RED_SEC = 2.0

SPEED_SIGN_DIAMETER = 0.6
SPEED_SIGN_BOTTOM_HEIGHT = 1.8
SPEED_SIGN_POLE_RADIUS = 0.05
SPEED_SIGN_SIDE_MARGIN = 0.8
SPEED_SIGN_SETBACK_M = 12.0

OVERSPEED_TOLERANCE_MPS = 0.5
OVERSPEED_RETURN_MPS = 0.1

DEFAULT_BUILDING_HEIGHT = 9.0
BUILDING_LEVEL_HEIGHT = 3.0
BUILDING_SIMPLIFY_TOLERANCE = 0.5
BUILDING_MIN_AREA = 8.0

DEFAULT_LANE_WIDTH = 3.25
MIN_ROAD_WIDTH = 5.0

GRID_CELL_SIZE = 1.0
GRID_MARGIN = 40.0

ROUTE_RESAMPLE_M = 2.0
